# \# Instalar paquetes

```{r}
if(!require(tidyverse)){
  install.packages("tidyverse")
  install.packages("tidytext")
}
if(!require(devtools)){
  install.packages("devtools")
}

if(!require(gutenbergr)){
  devtools::install_github("ropensci/gutenbergr")
}
```

# \# elegir corpus

```{r}
library(gutenbergr)
library(tidyverse)
library(tidytext)

```
# # Quiero ver si está Shakespeare
```{r}
gutenberg_works( author == "Shakespeare, William")
gutenberg_works(startsWith(author, "Shakespeare"))
```
# # Vemos qué hay en la librería, en español:
```{r}
gutenberg_works(languages = "es", author == "Shakespeare, William") 
```
# # Descargar
```{r}
Hamlet_Drama_en_cinco_actos <- 
  gutenberg_download(56454)
```

# # Ver
```{r}
View(Hamlet_Drama_en_cinco_actos)
```

### Análisis de ejemplo
```{r}
library(stringr)
Hamlet_Drama_en_cinco_actos %>% 
  mutate(n_words = str_count(text,"\\w")) # contamos palabras por linea
```
```{r}
Hamlet_Drama_en_cinco_actos %>% 
  mutate(n_words = stringr::str_count(text,"\\w")) %>% 
  summarize(
    Promedio = mean(n_words)
  )
```
# #Visualizar en *tiempo narrativo*
```{r}
Hamlet_Drama_en_cinco_actos %>% 
  mutate(n_words = stringr::str_count(text,"\\w")) %>% 
  mutate(index = row_number()) %>%  # Agregamos index 
  ggplot(aes(x = index, y = n_words))+
  geom_smooth()
```

