## Ejemplo distribución de frecuencias
```{r}
library(gutenbergr)
library(tidyverse)
library(tidytext)

Hamlet_Drama_en_cinco_actos <- 
  gutenberg_download(15115)
```

```{r}
Hamlet_Drama_en_cinco_actos %>% 
  mutate(n_words = stringr::str_count(text,"\\w")) %>% 
  select(n_words) %>% 
  table()
```
```{r}
novelas_y_teatro %>% 
  mutate(n_words = stringr::str_count(text,"\\w")) %>% 
  select(n_words) %>% 
  ggplot(aes(x=n_words))+
  geom_histogram()
```
```{r}
Hamlet_Drama_en_cinco_actos %>% 
  mutate(n_words = stringr::str_count(text,"\\w")) %>% 
  select(n_words) %>% 
  filter(n_words > 0) %>% 
  ggplot(aes(x=n_words))+
  geom_histogram()
```
```{r}
library(tidytext)
Hamlet_Drama_en_cinco_actos %>%
  unnest_tokens(output = word, input = text) %>% 
  group_by(word) %>% 
  count() %>% 
  arrange(desc(freq))
```
```{r}
library(tidytext)

Hamlet_Drama_en_cinco_actos %>%
  unnest_tokens(output = word, input = text) %>% 
  group_by(word) %>% 
  count() %>% 
  arrange(desc(n))
```
```{r}
Hamlet_Drama_en_cinco_actos %>%
  unnest_tokens(output = word, input = text) %>% 
  group_by(word) %>% 
  count() %>% 
  ggplot(aes(x=freq))+
  geom_histogram()+
  scale_x_log10()
```
```{r}
library(tidytext)
library(ggplot2)

Hamlet_Drama_en_cinco_actos %>%
  unnest_tokens(output = word, input = text) %>% 
  group_by(word) %>% 
  count() %>% 
  ggplot(aes(x = n)) +  # Cambiado de freq a n
  geom_histogram() +
  scale_x_log10()
```

